name: CD - Déploiement Hugging Face Space

on:
  push:
    branches:
      - main  # 🛑 Le CD ne se déclenche que sur la branche main
  workflow_dispatch:  # 🔘 Option pour lancer manuellement le CD

jobs:
  deploy:
    needs: ci  # ➕ Attend que le job CI passe avant de lancer le CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true  

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://Tbruand:$HF_TOKEN@huggingface.co/spaces/Tbruand/toxicheck || true
          git push space main --force